Update project.yml

diff --git a/.github/workflows/project.yml b/.github/workflows/project.yml
--- a/.github/workflows/project.yml
+++ b/.github/workflows/project.yml
@@ -56,15 +56,20 @@ jobs:
 
       - name: Create Database
         env:
-          PINGGY_URL: ${{ secrets.PINGGY_URL }}
+          PINGGY_URL: "rnqpv-41-150-33-214.a.free.pinggy.link,38971"
+          # ${{ secrets.PINGGY_URL }}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           SQL_USER: ${{ secrets.SQL_USER }}
           
         run: |
           # Test connection first
-          /opt/mssql-tools18/bin/sqlcmd -S "$PINGGT_URL" -U "$SQL_USER" -P "$DB_PASSWORD" \
-            -Q "SELECT 'Connection successful' AS Result" -b -o connect.log || (cat connect.log && exit 1)
+          echo "Testing connection to $PINGGY_HOST,$PINGGY_PORT..."
+          nc -zv $PINGGY_HOST $PINGGY_PORT || echo "::error::Pinggy tunnel unreachable"
             
           # Execute setup script
-          /opt/mssql-tools18/bin/sqlcmd -S "$PINGGY_URL" -U "$SQL_USER" -P "$DB_PASSWORD" \
-            -i "./DatabaseAdministration/SQLStatements/SetupDatabase.sql" -b -o output.log -V 16 -y 1000 || (cat output.log && exit 1)
+          /opt/mssql-tools18/bin/sqlcmd -S "$PINGGY_HOST,$PINGGY_PORT" -U "$SQL_USER" -P "$DB_PASSWORD" \
+          -Q "SELECT 1" -b -o connect.log || (cat connect.log && exit 1)
+
+          echo "✅ Connection successful!
+          # /opt/mssql-tools18/bin/sqlcmd -S "$PINGGY_URL" -U "$SQL_USER" -P "$DB_PASSWORD" \
+          #   -i "./DatabaseAdministration/SQLStatements/SetupDatabase.sql" -b -o output.log -V 16 -y 1000 || (cat output.log && exit 1)
