Update project.yml

diff --git a/.github/workflows/project.yml b/.github/workflows/project.yml
--- a/.github/workflows/project.yml
+++ b/.github/workflows/project.yml
@@ -56,9 +56,14 @@ jobs:
 
       - name: Create Database
         env:
-          SQL_HOST: ${{ secrets.PINGGY_URL }}
+          PINGGY_URL: ${{ secrets.PINGGY_URL }}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           SQL_USER: ${{ secrets.SQL_USER }}
           SQL_PORT: ${{ secrets.SQL_PORT }}
         run: |
-          /opt/mssql-tools18/bin/sqlcmd -S "$PINGGY_URL,$SQL_PORT" -U "$SQL_USER" -P "$DB_PASSWORD" -i "./DatabaseAdministration/SQLStatements/SetupDatabase.sql" -b -o sqlcmd.log if [ $? -ne 0 ]; then echo "::error::SQL script execution failed" cat sqlcmd.log exit 1 fi
+          /opt/mssql-tools18/bin/sqlcmd -S "$PINGGY_URL,$SQL_PORT" -U "$SQL_USER" -P "$DB_PASSWORD" -i "./DatabaseAdministration/SQLStatements/SetupDatabase.sql" -b -o sqlcmd.log
+          if [ $? -ne 0 ]; then
+            echo "::error::SQL script execution failed"
+            cat sqlcmd.log
+            exit 1
+          fi
